# Generated by Django 4.2.5 on 2023-09-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='carditem',
            options={'verbose_name': 'CardItem', 'verbose_name_plural': 'CardItems'},
        ),
    ]
