# Generated by Django 4.2.5 on 2023-09-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('cards', '0002_alter_card_options_alter_carditem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
